import * as monaco from 'monaco-editor';

export const editorOptions: monaco.editor.IStandaloneEditorConstructionOptions = {
  theme: 'vs-dark',
  language: 'markdown',
  mouseWheelZoom: true,
  wordWrap: 'on',
  automaticLayout: true,
  renderWhitespace: 'boundary',
  tabSize: 2,
  insertSpaces: true,
  wrappingIndent: 'same',
  smoothScrolling: true,
  lineDecorationsWidth: 0,
  cursorSmoothCaretAnimation: 'on',
  lineNumbers: 'off',
  minimap: {enabled: false},
  suggest: {
    showIcons: false,
    showStatusBar: false,
    showInlineDetails: false,
    filterGraceful: true,
    preview: false,
    snippetsPreventQuickSuggestions: false,
  },
  scrollbar: {
    horizontal: 'hidden',
    alwaysConsumeMouseWheel: false
  },
  contextmenu: false,
  fontSize: 14,
  fontFamily: 'monospace',
  glyphMargin: false,
  folding: false,
  fixedOverflowWidgets: true,
  overviewRulerLanes: 0,
  overviewRulerBorder: false,
  renderLineHighlight: 'none',
  renderLineHighlightOnlyWhenFocus: true,
  renderValidationDecorations: 'off',
  selectionHighlight: false,
  scrollBeyondLastLine: false,
  hideCursorInOverviewRuler: true,
  cursorBlinking: 'smooth',
};
